"""offsets.json -> src/offsets.h

The generated header carries only the *inputs* to runtime resolution (the anchor
pattern, the call/ripref offsets inside it, RTTI type names and vtable slots) plus
struct-field constants. Absolute RVAs are emitted solely as EXPECT_* values that
resolve.cpp logs for cross-checking - they are never used as a resolution path.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
meta = json.loads((ROOT / "offsets.json").read_text())

_seen = set()


def expect(name, rva):
    """Emit an EXPECT_ constant once; the same symbol can appear in both the
    anchor block and an RTTI slot block (e.g. REF_STEP_2C)."""
    if name in _seen:
        return []
    _seen.add(name)
    return [f"constexpr uintptr_t EXPECT_{name} = {rva};"]

L = [
    "// GENERATED by tools/gen_offsets.py - do not hand-edit.",
    "// Source of truth: offsets.json",
    "#pragma once",
    "#include <cstdint>",
    "#include <cstddef>",
    "",
    "namespace off {",
    "",
    f'// build: {meta["build"]["exe"]} ({meta["build"]["size"]} bytes)',
    f'constexpr uint32_t EXPECTED_EXE_SIZE = {meta["build"]["size"]};',
    "",
    "// ---- anchor: one unique pattern, everything else read out of it ----",
]

a = meta["anchor"]
L.append(f'constexpr char ANCHOR_PATTERN[] = "{a["pattern"]}";')
L += expect(a["name"], a["expect_rva"])
L.append("")

for name, c in a["calls"].items():
    L.append(f'constexpr uintptr_t CALLAT_{name} = {c["at"]};')
    L += expect(name, c["expect_rva"])
L.append("")

for name, r in a["riprefs"].items():
    L.append(f'constexpr uintptr_t RIPAT_{name} = {r["at"]};')
    L.append(f'constexpr uintptr_t RIPLEN_{name} = {r["len"]};')
    L += expect(name, r["expect_rva"])
L.append("")

L.append("// ---- secondary anchors: same idiom, different entry points ----")
for aname, sec in meta.get("anchors", {}).items():
    L.append(f'constexpr char ANCHOR_{aname}_PATTERN[] = "{sec["pattern"]}";')
    L += expect(aname, sec["expect_rva"])
    for name, c in sec.get("calls", {}).items():
        L.append(f'constexpr uintptr_t CALLAT_{name} = {c["at"]};')
        L += expect(name, c["expect_rva"])
    for name, r in sec.get("riprefs", {}).items():
        L.append(f'constexpr uintptr_t RIPAT_{name} = {r["at"]};')
        L.append(f'constexpr uintptr_t RIPLEN_{name} = {r["len"]};')
        L += expect(name, r["expect_rva"])
L.append("")

L.append("// ---- standalone byte patterns ----")
for name, p in meta.get("patterns", {}).items():
    L.append(f'constexpr char PATTERN_{name}[] = "{p["pattern"]}";')
    L += expect(name, p["expect_rva"])
L.append("")

L.append("// ---- RTTI: type descriptor -> COL -> vftable -> slot ----")
for cls, info in meta["rtti"].items():
    L.append(f'constexpr char TYPENAME_{cls}[] = "{info["type_name"]}";')
    for name, s in info["slots"].items():
        L.append(f'constexpr int SLOT_{name} = {s["slot"]};')
        L += expect(name, s["expect_rva"])
        if "space" in s:
            L.append(f'constexpr size_t SPACE_{name} = {s["space"]};')
L.append("")

L.append("// ---- struct field offsets and mode constants ----")
for name, v in meta["constants"].items():
    L.append(f"constexpr uintptr_t C_{name} = {v};")

L.append("")
L.append("}  // namespace off")

out = ROOT / "src" / "offsets.h"
out.write_text("\n".join(L) + "\n")
print(f"wrote {out.relative_to(ROOT)} ({len(L)} lines)")
