// GENERATED by tools/gen_offsets.py - do not hand-edit.
// Source of truth: offsets.json
#pragma once
#include <cstdint>
#include <cstddef>

namespace off {

// build: Yakuza4.exe (28396336 bytes)
constexpr uint32_t EXPECTED_EXE_SIZE = 28396336;

// ---- anchor: one unique pattern, everything else read out of it ----
constexpr char ANCHOR_PATTERN[] = "40 53 48 83 EC 30 C5 FA 10 15 3E";
constexpr uintptr_t EXPECT_REF_STEP_2C = 0xB5C320;

constexpr uintptr_t CALLAT_TRANSITION_SETUP = 0x24;
constexpr uintptr_t EXPECT_TRANSITION_SETUP = 0xB4ADC0;
constexpr uintptr_t CALLAT_COMMIT_FLAGS = 0x30;
constexpr uintptr_t EXPECT_COMMIT_FLAGS = 0xBF6AB0;
constexpr uintptr_t CALLAT_OPEN_SCREEN = 0x48;
constexpr uintptr_t EXPECT_OPEN_SCREEN = 0x3272D0;
constexpr uintptr_t CALLAT_SET_NEXT_STEP = 0x55;
constexpr uintptr_t EXPECT_SET_NEXT_STEP = 0xB52B20;
constexpr uintptr_t CALLAT_POST_OPEN_NOTIFY = 0x73;
constexpr uintptr_t EXPECT_POST_OPEN_NOTIFY = 0xB4A600;

constexpr uintptr_t RIPAT_G_FLAG_MGR = 0x29;
constexpr uintptr_t RIPLEN_G_FLAG_MGR = 7;
constexpr uintptr_t EXPECT_G_FLAG_MGR = 0x1A1FA20;
constexpr uintptr_t RIPAT_G_MAIN_MGR = 0x35;
constexpr uintptr_t RIPLEN_G_MAIN_MGR = 7;
constexpr uintptr_t EXPECT_G_MAIN_MGR = 0x197C838;
constexpr uintptr_t RIPAT_K_FLOAT = 0x06;
constexpr uintptr_t RIPLEN_K_FLOAT = 8;
constexpr uintptr_t EXPECT_K_FLOAT = 0x122D46C;

// ---- standalone byte patterns ----
constexpr char PATTERN_SET_RESULT_VARIANT[] = "48 83 EC 28 89 91 B8 01 00 00 44 89 81 BC 01 00 00";
constexpr uintptr_t EXPECT_SET_RESULT_VARIANT = 0x3A46D0;

// ---- RTTI: type descriptor -> COL -> vftable -> slot ----
constexpr char TYPENAME_COLOSSEUM_EXTRA[] = ".?AVCMissionMacroColosseumExtra@@";
constexpr int SLOT_STEP_2C_STUB = 62;
constexpr uintptr_t EXPECT_STEP_2C_STUB = 0xB5C3C0;
constexpr size_t SPACE_STEP_2C_STUB = 16;
constexpr int SLOT_STEP_2D_STUB = 63;
constexpr uintptr_t EXPECT_STEP_2D_STUB = 0xB60940;
constexpr size_t SPACE_STEP_2D_STUB = 16;
constexpr char TYPENAME_COLOSSEUM[] = ".?AVCMissionMacroColosseum@@";
constexpr int SLOT_REF_STEP_2C = 62;
constexpr int SLOT_STEP_2D_WORKING = 63;
constexpr uintptr_t EXPECT_STEP_2D_WORKING = 0xB60910;
constexpr char TYPENAME_ACTION_COLOSSEUM_EXTRA[] = ".?AVCActionColosseumExtra@@";

// ---- struct field offsets and mode constants ----
constexpr uintptr_t C_SCREEN_RESULT = 220;
constexpr uintptr_t C_STEP_2D = 45;
constexpr uintptr_t C_STEP_2E = 46;
constexpr uintptr_t C_ACTION_OFFSET = 0xBA0;
constexpr uintptr_t C_KILL_COUNT_OFFSET = 0x208;
constexpr uintptr_t C_CUR_STEP_FIELD = 0x128;
constexpr uintptr_t C_NEXT_STEP_FIELD = 0x12C;
constexpr uintptr_t C_MISSION_FIELD = 0x8;
constexpr uintptr_t C_OPENSCREEN_ARG3_FIELD = 0x1F0;
constexpr uintptr_t C_SCREEN_SLOT_BASE = 0x1E8;
constexpr uintptr_t C_SCREEN_LOADED_FIELD = 0x1A8;
constexpr uintptr_t C_SCREEN_VARIANT_FIELD = 0x1B8;
constexpr uintptr_t C_SCREEN_DRAWGATE_FIELD = 0x1C0;
constexpr uintptr_t C_SCREEN_LAYOUT_FIELD = 0x1B0;
constexpr uintptr_t C_LAYOUT_PAGE_ARRAY = 0x110;
constexpr uintptr_t C_LAYOUT_PAGE_STRIDE = 0x30;
constexpr uintptr_t C_PAGE_ELEM_FIELD = 0x10;
constexpr uintptr_t C_ELEM_FLAGS_FIELD = 0x2C;
constexpr uintptr_t C_ELEM_SUPPRESS_FIELD = 0xBC;

}  // namespace off
