// GENERATED by tools/gen_offsets.py - do not hand-edit.
// Source of truth: offsets.json
#pragma once
#include <cstdint>
#include <cstddef>

namespace off {

// build: Yakuza4.exe (28396336 bytes)
constexpr uint32_t EXPECTED_EXE_SIZE = 28396336;

// ---- anchor: one unique pattern, everything else read out of it ----
constexpr char ANCHOR_PATTERN[] = "40 53 48 83 EC 30 C5 FA 10 15 3E";
constexpr uintptr_t EXPECT_REF_STEP_2C = 0xB5C320;

constexpr uintptr_t CALLAT_TRANSITION_SETUP = 0x24;
constexpr uintptr_t EXPECT_TRANSITION_SETUP = 0xB4ADC0;
constexpr uintptr_t CALLAT_COMMIT_FLAGS = 0x30;
constexpr uintptr_t EXPECT_COMMIT_FLAGS = 0xBF6AB0;
constexpr uintptr_t CALLAT_OPEN_SCREEN = 0x48;
constexpr uintptr_t EXPECT_OPEN_SCREEN = 0x3272D0;
constexpr uintptr_t CALLAT_SET_NEXT_STEP = 0x55;
constexpr uintptr_t EXPECT_SET_NEXT_STEP = 0xB52B20;
constexpr uintptr_t CALLAT_POST_OPEN_NOTIFY = 0x73;
constexpr uintptr_t EXPECT_POST_OPEN_NOTIFY = 0xB4A600;

constexpr uintptr_t RIPAT_G_FLAG_MGR = 0x29;
constexpr uintptr_t RIPLEN_G_FLAG_MGR = 7;
constexpr uintptr_t EXPECT_G_FLAG_MGR = 0x1A1FA20;
constexpr uintptr_t RIPAT_G_MAIN_MGR = 0x35;
constexpr uintptr_t RIPLEN_G_MAIN_MGR = 7;
constexpr uintptr_t EXPECT_G_MAIN_MGR = 0x197C838;
constexpr uintptr_t RIPAT_K_FLOAT = 0x06;
constexpr uintptr_t RIPLEN_K_FLOAT = 8;
constexpr uintptr_t EXPECT_K_FLOAT = 0x122D46C;

// ---- secondary anchors: same idiom, different entry points ----
constexpr char ANCHOR_DLC_FLAG_BRIDGE_PATTERN[] = "BA 17 00 00 00 48 8D 0D ? ? ? ? E8 ? ? ? ? 48";
constexpr uintptr_t EXPECT_DLC_FLAG_BRIDGE = 0xBCD251;
constexpr uintptr_t CALLAT_IS_DLC_OWNED = 0x0C;
constexpr uintptr_t EXPECT_IS_DLC_OWNED = 0xCB5970;
constexpr uintptr_t CALLAT_SET_FLAG_ALIAS = 0x20;
constexpr uintptr_t EXPECT_SET_FLAG_ALIAS = 0x28A7A0;
constexpr char ANCHOR_IS_DLC_OWNED_PATTERN[] = "8B C2 48 8D 0D ? ? ? ? 48 C1 E8 05 44";
constexpr uintptr_t RIPAT_G_DLC_MASK = 0x02;
constexpr uintptr_t RIPLEN_G_DLC_MASK = 7;
constexpr uintptr_t EXPECT_G_DLC_MASK = 0x1A21C50;
constexpr char ANCHOR_NETRANK_BIND_PATTERN[] = "48 89 5C 24 10 57 48 83 EC 20 48 8B D9 33 FF 48 8B 09";
constexpr uintptr_t EXPECT_NETRANK_BIND = 0x85E330;
constexpr uintptr_t CALLAT_LAYOUT_IS_LOADING = 0x12;
constexpr uintptr_t EXPECT_LAYOUT_IS_LOADING = 0x4843E0;
constexpr uintptr_t CALLAT_LAYOUT_PAGE_READY = 0x24;
constexpr uintptr_t EXPECT_LAYOUT_PAGE_READY = 0x484510;
constexpr uintptr_t CALLAT_LAYOUT_GET_PANE = 0x57;
constexpr uintptr_t EXPECT_LAYOUT_GET_PANE = 0x484220;
constexpr uintptr_t RIPAT_G_LAYOUT_RES = 0x3C;
constexpr uintptr_t RIPLEN_G_LAYOUT_RES = 7;
constexpr uintptr_t EXPECT_G_LAYOUT_RES = 0x1980D18;
constexpr char ANCHOR_MISSION_TICK_PATTERN[] = "48 8B 4B 50 48 85 C9 0F 84 ? ? ? ? 48 39";
constexpr uintptr_t EXPECT_MISSION_TICK = 0xB6AD7D;
constexpr uintptr_t RIPAT_G_MISSION_MGR = 0x2C1;
constexpr uintptr_t RIPLEN_G_MISSION_MGR = 7;
constexpr uintptr_t EXPECT_G_MISSION_MGR = 0x1A195E0;
constexpr char ANCHOR_LAYOUT_NAMES_READ_PATTERN[] = "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 57 48 83 EC 20 48 8B 3D ? ? ? ? 33 ED 8B DD 8D 75 28";
constexpr uintptr_t EXPECT_LAYOUT_NAMES_READ = 0x482E60;
constexpr uintptr_t RIPAT_G_LAYOUT_NAMES = 0x14;
constexpr uintptr_t RIPLEN_G_LAYOUT_NAMES = 7;
constexpr uintptr_t EXPECT_G_LAYOUT_NAMES = 0x19807F8;
constexpr char ANCHOR_LAYOUT_SLOT_COUNT_READ_PATTERN[] = "48 83 EC 28 3B 0D ? ? ? ? 73 44 8B C1";
constexpr uintptr_t EXPECT_LAYOUT_SLOT_COUNT_READ = 0x487860;
constexpr uintptr_t RIPAT_G_LAYOUT_SLOT_COUNT = 0x04;
constexpr uintptr_t RIPLEN_G_LAYOUT_SLOT_COUNT = 6;
constexpr uintptr_t EXPECT_G_LAYOUT_SLOT_COUNT = 0x1980D20;

// ---- standalone byte patterns ----
constexpr char PATTERN_SET_RESULT_VARIANT[] = "48 83 EC 28 89 91 B8 01 00 00 44 89 81 BC 01 00 00";
constexpr uintptr_t EXPECT_SET_RESULT_VARIANT = 0x3A46D0;
constexpr char PATTERN_HEAP_PUSH[] = "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 48 63 05";
constexpr uintptr_t EXPECT_HEAP_PUSH = 0x3C6530;
constexpr char PATTERN_HEAP_ALLOC[] = "48 89 4C 24 08 57 48 83 EC 30 48 C7 44 24 20 FE FF FF FF 48 89 5C 24 50 48 8B 05";
constexpr uintptr_t EXPECT_HEAP_ALLOC = 0x3C6230;
constexpr char PATTERN_HEAP_POP[] = "48 83 EC 38 8B 05 ? ? ? ? 48 8D";
constexpr uintptr_t EXPECT_HEAP_POP = 0x3C69C0;
constexpr char PATTERN_LAYOUT_LOAD[] = "4C 8B DC 56 41 54 41 56 48";
constexpr uintptr_t EXPECT_LAYOUT_LOAD = 0x483AA0;
constexpr char PATTERN_NETRANK_CTOR[] = "33 C0 33 D2 48 89 11 48 89 41";
constexpr uintptr_t EXPECT_NETRANK_CTOR = 0x85DE90;
constexpr char PATTERN_NETRANK_LOADLAYOUT[] = "40 53 48 83 EC 30 48 C7 44 24 20 FE FF FF FF 48 8B D9 B9 28 01 00 00 E8 ? ? ? ? 48 89 44 24 40 48 85 C0 74 13";
constexpr uintptr_t EXPECT_NETRANK_LOADLAYOUT = 0x85E110;
constexpr char PATTERN_NETRANK_SHOW[] = "48 89 5C 24 08 57 48 83 EC 20 48 63 DA 48 8B F9 45 85 C0 75 2A 8B D3 E8 ? ? ? ? 85 C0 74 48 48 8B 4C DF 08";
constexpr uintptr_t EXPECT_NETRANK_SHOW = 0x85E020;
constexpr char PATTERN_NETRANK_DRAW[] = "40 53 48 83 EC 20 33 D2 48 8B D9 E8 ? ? ? ? 85 C0 74 38";
constexpr uintptr_t EXPECT_NETRANK_DRAW = 0x85DEC0;
constexpr char PATTERN_TEXPAR_LOAD[] = "40 53 55 56 57 41 56 48 81 EC 60 01 00 00 48 C7 44 24 30 FE FF FF FF 48 8B 05 ? ? ? ? 48 33 C4 48 89 84 24 50 01 00 00 49 8B E8 48 63";
constexpr uintptr_t EXPECT_TEXPAR_LOAD = 0x482780;
constexpr char PATTERN_BUILD_PAGES[] = "40 55 56 57 41 56 41 57 48 83 EC 40 48 C7 44 24 30 FE FF FF FF 48 89 5C 24 78 44";
constexpr uintptr_t EXPECT_BUILD_PAGES = 0x484510;
constexpr char PATTERN_GET_PAGE[] = "4C 8B 81 10 01 00 00 4D";
constexpr uintptr_t EXPECT_GET_PAGE = 0x484220;
constexpr char PATTERN_SET_SUPPRESS[] = "89 91 BC 00 00 00 C3 CC CC CC CC";
constexpr uintptr_t EXPECT_SET_SUPPRESS = 0x48AC40;
constexpr char PATTERN_HEAP_FREE[] = "48 85 C9 74 42 53 48 83 EC 30";
constexpr uintptr_t EXPECT_HEAP_FREE = 0x3C64D0;
constexpr char PATTERN_LAYOUT_RELEASE[] = "40 53 48 83 EC 30 48 C7 44 24 20 FE FF FF FF 48 8B D9 48 8D 05 ? ? ? ? 48 89 01 48 8B 89 20 01";
constexpr uintptr_t EXPECT_LAYOUT_RELEASE = 0x483EB0;

// ---- RTTI: type descriptor -> COL -> vftable -> slot ----
constexpr char TYPENAME_COLOSSEUM_EXTRA[] = ".?AVCMissionMacroColosseumExtra@@";
constexpr int SLOT_STEP_2C_STUB = 62;
constexpr uintptr_t EXPECT_STEP_2C_STUB = 0xB5C3C0;
constexpr size_t SPACE_STEP_2C_STUB = 16;
constexpr int SLOT_STEP_2D_STUB = 63;
constexpr uintptr_t EXPECT_STEP_2D_STUB = 0xB60940;
constexpr size_t SPACE_STEP_2D_STUB = 16;
constexpr char TYPENAME_COLOSSEUM[] = ".?AVCMissionMacroColosseum@@";
constexpr int SLOT_REF_STEP_2C = 62;
constexpr int SLOT_STEP_2D_WORKING = 63;
constexpr uintptr_t EXPECT_STEP_2D_WORKING = 0xB60910;
constexpr char TYPENAME_ACTION_COLOSSEUM_EXTRA[] = ".?AVCActionColosseumExtra@@";

// ---- struct field offsets and mode constants ----
constexpr uintptr_t C_SCREEN_RESULT = 220;
constexpr uintptr_t C_STEP_2D = 45;
constexpr uintptr_t C_STEP_2E = 46;
constexpr uintptr_t C_ACTION_OFFSET = 0xBA0;
constexpr uintptr_t C_KILL_COUNT_OFFSET = 0x208;
constexpr uintptr_t C_CUR_STEP_FIELD = 0x128;
constexpr uintptr_t C_NEXT_STEP_FIELD = 0x12C;
constexpr uintptr_t C_MISSION_FIELD = 0x8;
constexpr uintptr_t C_OPENSCREEN_ARG3_FIELD = 0x1F0;
constexpr uintptr_t C_SCREEN_SLOT_BASE = 0x1E8;
constexpr uintptr_t C_SCREEN_LOADED_FIELD = 0x1A8;
constexpr uintptr_t C_SCREEN_VARIANT_FIELD = 0x1B8;
constexpr uintptr_t C_SCREEN_DRAWGATE_FIELD = 0x1C0;
constexpr uintptr_t C_SCREEN_LAYOUT_FIELD = 0x1B0;
constexpr uintptr_t C_LAYOUT_PAGE_ARRAY = 0x110;
constexpr uintptr_t C_LAYOUT_PAGE_STRIDE = 0x30;
constexpr uintptr_t C_PAGE_ELEM_FIELD = 0x10;
constexpr uintptr_t C_ELEM_FLAGS_FIELD = 0x2C;
constexpr uintptr_t C_ELEM_SUPPRESS_FIELD = 0xBC;
constexpr uintptr_t C_NETRANK_PANEL_SIZE = 0x28;
constexpr uintptr_t C_NETRANK_LAYOUT_SIZE = 0x128;
constexpr uintptr_t C_NETRANK_VALUE_FIELD = 0x20;
constexpr uintptr_t C_HEAP_ID_UI = 10;
constexpr uintptr_t C_FLAGMGR_TABLE_FIELD = 0x990;
constexpr uintptr_t C_FLAG_ALIAS_SURVIVAL_TAG_SP = 0x648;
constexpr uintptr_t C_FLAG_ALIAS_SPEED_KING = 0x649;
constexpr uintptr_t C_FLAG_ALIAS_FASTEST_KILLER = 0x64A;
constexpr uintptr_t C_DLC_BIT_SURVIVAL_TAG_SP = 0x17;
constexpr uintptr_t C_DLC_BIT_SPEED_KING = 0x18;
constexpr uintptr_t C_DLC_BIT_FASTEST_KILLER = 0x19;
constexpr uintptr_t C_TEXPAR_TABLE_DISP_AT = 0x55;
constexpr uintptr_t C_G_LAYOUT_TEXPAR_EXPECT = 0x1980A80;
constexpr uintptr_t C_LAYOUT_RES_INDEX_FIELD = 0x8;
constexpr uintptr_t C_LAYOUT_RES_STRIDE = 0x70;
constexpr uintptr_t C_LAYOUT_RES_COUNT_FIELD = 0x18;
constexpr uintptr_t C_G_LAYOUT_STATE_EXPECT = 0x19809E0;
constexpr uintptr_t C_LAYOUT_SLOT_COUNT = 40;
constexpr uintptr_t C_MISSIONMGR_MACRO_FIELD = 0x58;
constexpr uintptr_t C_MISSIONMGR_STATE_FIELD = 0x30;
constexpr uintptr_t C_MACRO_ID_FIELD = 0x84;
constexpr uintptr_t C_LAYOUT_NAME_FIELD = 0xC;
constexpr uintptr_t C_LAYOUT_FLAGS_FIELD = 0x118;
constexpr uintptr_t C_RES_FLAGS_FIELD = 0x0;
constexpr uintptr_t C_RES_CSB_FIELD = 0x8;
constexpr uintptr_t C_SCREEN_ID_RANGE_LO = 0x12363E0;
constexpr uintptr_t C_SCREEN_ID_RANGE_HI = 0x1236850;
constexpr uintptr_t C_SCREEN_FACTORY_TABLE = 0x16E4910;
constexpr uintptr_t C_SCREEN_ID_RANGE_COUNT = 281;
constexpr uintptr_t C_SCREEN_ID_CAPTION = 220;
constexpr uintptr_t C_SCREEN_ID_BATTLE_RESULT = 222;
constexpr uintptr_t C_SCREEN_ID_ONIGOKKO_RESULT = 223;
constexpr uintptr_t C_SCREEN_ID_TOUGIJYO_RESULT = 225;

}  // namespace off
